import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';import {Box,Button,MenuItem,Select,Stack,TextField,Typography} from '@mui/material';import {Plot} from '../components/Plot';import {Link,useParams} from 'react-router-dom';
import {api} from '../services/api';import type {Alert,Asset,Measurement,RecordRow,RulPrediction,WorkOrder} from '../types';import {ChartShell,DataTable,ErrorState,KpiCard,LoadingState,PageGrid,PageHeader,SectionCard,StatusChip} from '../components/shared';
const layout={paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#a9bfd1'},margin:{l:45,r:15,t:20,b:45},autosize:true};
function useApi<T>(key:string,path:string){return useQuery({queryKey:[key,path],queryFn:()=>api.get<T>(path),refetchInterval:5000})}
function State({query,children}:{query:any;children:(data:any)=>React.ReactNode}){if(query.isLoading)return <LoadingState/>;if(query.error)return <ErrorState message={query.error.message}/>;return <>{children(query.data?.data)}</>}
export function OverviewPage(){const q=useApi<any>('overview','/overview');return <><PageHeader title="Vue générale" subtitle="État opérationnel consolidé de la ligne"/><State query={q}>{d=><><PageGrid><KpiCard label="Équipements" value={d.counts.assets}/><KpiCard label="Anomalies analysées" value={d.counts.anomaly_results}/><KpiCard label="Ordres actifs" value={d.counts.active_work_orders} accent="#ffb547"/><KpiCard label="Alertes ouvertes" value={d.counts.unacknowledged_alerts} accent="#ff647c"/></PageGrid><Box sx={{mt:2}}><SectionCard title="Dernières télémétries"><DataTable rows={d.latest_measurements} columns={['timestamp','equipment_id','temperature','vibration','health_score','is_anomaly']}/></SectionCard></Box></>}</State></>}
export function LinePage(){const q=useApi<Measurement[]>('latest','/measurements/latest?limit=100');return <><PageHeader title="Ligne industrielle" subtitle="Capteurs et santé en temps réel"/><State query={q}>{rows=><SectionCard title="Santé par équipement"><ChartShell><Plot data={[{x:rows.map((x:Measurement)=>x.equipment_id),y:rows.map((x:Measurement)=>x.health_score),type:'bar',marker:{color:'#39d0c4'}}]} layout={{...layout,title:{text:'Score de santé'}}} useResizeHandler style={{width:'100%',height:'100%'}}/></ChartShell></SectionCard>}</State></>}
export function AssetsPage(){const q=useApi<Asset[]>('assets','/assets?page_size=100');return <><PageHeader title="Équipements" subtitle="Inventaire des actifs du jumeau numérique"/><State query={q}>{rows=><Stack sx={{gap:2}}>{rows.map((x:Asset)=><SectionCard key={x.equipment_id} title={x.display_name}><Stack direction="row" sx={{justifyContent:'space-between'}}><Typography>{x.equipment_type} · Santé {x.health_score?.toFixed(1)??'—'}%</Typography><Button component={Link} to={`/assets/${x.equipment_id}`}>Détails</Button></Stack></SectionCard>)}</Stack>}</State></>}
export function AssetDetailPage(){const {equipmentId}=useParams();const q=useApi<any>('asset-latest',`/assets/${equipmentId}/latest`);const timeline=useApi<Measurement[]>('asset-timeline',`/assets/${equipmentId}/timeline?limit=250`);return <><PageHeader title={equipmentId??'Équipement'} subtitle="Diagnostic opérationnel détaillé"/><State query={q}>{d=><PageGrid><KpiCard label="Température" value={`${d.measurement?.temperature??'—'} °C`}/><KpiCard label="Vibration" value={`${d.measurement?.vibration??'—'} mm/s`}/><KpiCard label="Diagnostic" value={d.diagnosis?.diagnosis??'—'}/><KpiCard label="RUL" value={`${d.rul?.predicted_rul_hours?.toFixed(1)??'—'} h`}/></PageGrid>}</State><Box sx={{mt:2}}><State query={timeline}>{rows=><SectionCard title="Tendance santé"><ChartShell><Plot data={[{x:rows.map((x:Measurement)=>x.timestamp),y:rows.map((x:Measurement)=>x.health_score),type:'scatter',mode:'lines',line:{color:'#39d0c4'}}]} layout={layout} useResizeHandler style={{width:'100%',height:'100%'}}/></ChartShell></SectionCard>}</State></Box></>}
function TablePage({title,subtitle,path,columns}:{title:string;subtitle:string;path:string;columns:string[]}){const q=useApi<RecordRow[]>(title,path);return <><PageHeader title={title} subtitle={subtitle}/><State query={q}>{rows=><DataTable rows={rows} columns={columns}/>}</State></>}
export const AnomaliesPage=()=> <TablePage title="Anomalies" subtitle="Résultats combinés seuils et Isolation Forest" path="/anomalies?page_size=100" columns={['timestamp','equipment_id','is_anomaly','anomaly_score','detected_sensors']}/>;
export function RulPage(){const q=useApi<RulPrediction[]>('rul','/rul/latest');return <><PageHeader title="Durée de vie restante" subtitle="Prédictions RUL et niveaux de risque"/><State query={q}>{rows=><><PageGrid>{rows.map((x:RulPrediction)=><KpiCard key={x.equipment_id} label={`${x.equipment_id} · ${x.risk_level}`} value={`${x.predicted_rul_hours.toFixed(1)} h`}/>)}</PageGrid><Box sx={{mt:2}}><DataTable rows={rows as unknown as RecordRow[]} columns={['equipment_id','predicted_rul_hours','risk_level','prediction_confidence','timestamp']}/></Box></>}</State></>}
export function MaintenancePage(){const q=useApi<WorkOrder[]>('wo','/work-orders?page_size=100');const client=useQueryClient();const update=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api.patch(`/work-orders/${id}/status`,{status}),onSuccess:()=>client.invalidateQueries({queryKey:['wo']})});return <><PageHeader title="Maintenance" subtitle="Planification et suivi des ordres de travail"/><State query={q}>{rows=><Stack sx={{gap:2}}>{rows.map((x:WorkOrder)=><SectionCard key={x.work_order_id} title={x.work_order_id}><Stack direction={{xs:'column',md:'row'}} sx={{gap:2,alignItems:'center'}}><Typography sx={{flex:1}}>{x.equipment_id} · {x.priority}</Typography><StatusChip value={x.status}/><Select size="small" value={x.status} onChange={e=>update.mutate({id:x.work_order_id,status:e.target.value})}>{['proposed','scheduled','in_progress','completed','blocked','cancelled'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></Stack></SectionCard>)}</Stack>}</State></>}
export const AgentsPage=()=> <TablePage title="Agents" subtitle="Santé des neuf agents SPADE" path="/agents" columns={['agent_id','status','messages_processed','errors_count','queue_size','average_processing_time_ms']}/>;
export function AlertsPage(){const q=useApi<Alert[]>('alerts','/alerts?page_size=100');const client=useQueryClient();const ack=useMutation({mutationFn:(id:string)=>api.patch(`/alerts/${id}/acknowledge`),onSuccess:()=>client.invalidateQueries({queryKey:['alerts']})});return <><PageHeader title="Alertes" subtitle="Événements nécessitant une attention" actions={<Button variant="contained" onClick={()=>api.post('/alerts/acknowledge-all').then(()=>client.invalidateQueries({queryKey:['alerts']}))}>Tout acquitter</Button>}/><State query={q}>{rows=><Stack sx={{gap:2}}>{rows.map((x:Alert)=><SectionCard key={x.alert_id} title={x.title}><Stack direction="row" sx={{gap:2,alignItems:'center'}}><StatusChip value={x.level}/><Typography sx={{flex:1}}>{x.message}</Typography><Button disabled={x.acknowledged} onClick={()=>ack.mutate(x.alert_id)}>{x.acknowledged?'Acquittée':'Acquitter'}</Button></Stack></SectionCard>)}</Stack>}</State></>}
export const TracesPage=()=> <TablePage title="Traces pipeline" subtitle="Traçabilité de bout en bout" path="/traces?page_size=100" columns={['trace_id','equipment_id','status','steps_count','last_step','started_at']}/>;
export function RunsPage(){const q=useApi<RecordRow[]>('runs','/system-runs?page_size=100');const [scenario,setScenario]=React.useState('normal');const client=useQueryClient();const start=()=>api.post('/system-runs/start',{scenario,mode:'embedded',speed:20,max_measurements:100}).then(()=>client.invalidateQueries({queryKey:['runs']}));return <><PageHeader title="Exécutions" subtitle="Pilotage local des scénarios simulés" actions={<Stack direction="row"><Select size="small" value={scenario} onChange={e=>setScenario(e.target.value)}>{['normal','bearing_wear','pump_cavitation','emergency','resource_unavailable','agent_unavailable','duplicate_message'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select><Button variant="contained" onClick={start}>Démarrer</Button></Stack>}/><State query={q}>{rows=><DataTable rows={rows} columns={['run_id','scenario','mode','status','started_at','completed_at']}/>}</State></>}
export function SettingsPage(){return <><PageHeader title="Paramètres" subtitle="Configuration locale et sécurisée"/><SectionCard title="Connexion"><Stack sx={{gap:2}}><TextField label="API" value="http://127.0.0.1:8000/api/v1" slotProps={{input:{readOnly:true}}}/><TextField label="WebSocket" value="ws://127.0.0.1:8000/ws/dashboard" slotProps={{input:{readOnly:true}}}/><Typography color="text.secondary">Les scénarios utilisent exclusivement des données synthétiques. Aucune commande automate n'est exposée.</Typography></Stack></SectionCard></>}
import React from 'react';
