from __future__ import annotations
from datetime import datetime,timezone
from sqlalchemy import Boolean,Float,Integer,String,Text,Index
from sqlalchemy.orm import Mapped,mapped_column
from .database import Base

def now()->str:return datetime.now(timezone.utc).isoformat()
class IdMixin:
    id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True)
class Asset(IdMixin,Base):
    __tablename__="assets";equipment_id:Mapped[str]=mapped_column(String(80),unique=True,index=True);equipment_type:Mapped[str]=mapped_column(String(30),index=True);line_id:Mapped[str]=mapped_column(String(40),index=True,default="line_01");display_name:Mapped[str]=mapped_column(String(120));parent_equipment_id:Mapped[str|None]=mapped_column(String(80));status:Mapped[str]=mapped_column(String(30),index=True,default="unknown");health_score:Mapped[float|None]=mapped_column(Float);last_seen_at:Mapped[str|None]=mapped_column(String(40),index=True);created_at:Mapped[str]=mapped_column(String(40),default=now);updated_at:Mapped[str]=mapped_column(String(40),default=now,onupdate=now)
class SensorMeasurement(IdMixin,Base):
    __tablename__="sensor_measurements";timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);equipment_type:Mapped[str]=mapped_column(String(30),index=True);temperature:Mapped[float|None]=mapped_column(Float);vibration:Mapped[float|None]=mapped_column(Float);rpm:Mapped[float|None]=mapped_column(Float);current:Mapped[float|None]=mapped_column(Float);load:Mapped[float|None]=mapped_column(Float);pressure:Mapped[float|None]=mapped_column(Float);flow_rate:Mapped[float|None]=mapped_column(Float);conveyor_speed:Mapped[float|None]=mapped_column(Float);slip_rate:Mapped[float|None]=mapped_column(Float);health_score:Mapped[float|None]=mapped_column(Float);operating_state:Mapped[str|None]=mapped_column(String(30));is_anomaly:Mapped[bool]=mapped_column(Boolean,default=False)
    __table_args__=(Index("uq_measurement_natural","timestamp","equipment_id",unique=True),)
class AnomalyResult(IdMixin,Base):
    __tablename__="anomaly_results";timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);is_anomaly:Mapped[bool]=mapped_column(Boolean,index=True);threshold_prediction:Mapped[bool]=mapped_column(Boolean);isolation_forest_prediction:Mapped[bool]=mapped_column(Boolean);anomaly_score:Mapped[float|None]=mapped_column(Float);detected_sensors:Mapped[str|None]=mapped_column(Text);explanation:Mapped[str|None]=mapped_column(Text)
    __table_args__=(Index("uq_anomaly_natural","timestamp","equipment_id",unique=True),)
class FaultDiagnosis(IdMixin,Base):
    __tablename__="fault_diagnoses";timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);diagnosis:Mapped[str]=mapped_column(String(80),index=True);confidence:Mapped[float]=mapped_column(Float);severity:Mapped[str]=mapped_column(String(30),index=True);responsible_sensors:Mapped[str|None]=mapped_column(Text);explanation:Mapped[str|None]=mapped_column(Text)
    __table_args__=(Index("uq_diagnosis_natural","timestamp","equipment_id",unique=True),)
class RULPrediction(IdMixin,Base):
    __tablename__="rul_predictions";timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);predicted_rul_steps:Mapped[float]=mapped_column(Float);predicted_rul_hours:Mapped[float]=mapped_column(Float);rul_lower_bound:Mapped[float|None]=mapped_column(Float);rul_upper_bound:Mapped[float|None]=mapped_column(Float);prediction_confidence:Mapped[float|None]=mapped_column(Float);risk_level:Mapped[str]=mapped_column(String(30),index=True);responsible_features:Mapped[str|None]=mapped_column(Text);explanation:Mapped[str|None]=mapped_column(Text)
    __table_args__=(Index("uq_rul_natural","timestamp","equipment_id",unique=True),)
class MaintenanceRecommendation(IdMixin,Base):
    __tablename__="maintenance_recommendations";timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);maintenance_strategy:Mapped[str]=mapped_column(String(60));recommended_action:Mapped[str]=mapped_column(Text);priority:Mapped[str]=mapped_column(String(30),index=True);priority_score:Mapped[float|None]=mapped_column(Float);recommended_start:Mapped[str|None]=mapped_column(String(40));recommended_deadline:Mapped[str|None]=mapped_column(String(40));estimated_duration_hours:Mapped[float|None]=mapped_column(Float);required_skills:Mapped[str|None]=mapped_column(Text);required_parts:Mapped[str|None]=mapped_column(Text);shutdown_required:Mapped[bool]=mapped_column(Boolean);estimated_total_cost:Mapped[float|None]=mapped_column(Float);confidence:Mapped[float|None]=mapped_column(Float);explanation:Mapped[str|None]=mapped_column(Text)
class WorkOrder(IdMixin,Base):
    __tablename__="work_orders";work_order_id:Mapped[str]=mapped_column(String(80),unique=True,index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);diagnosed_fault:Mapped[str|None]=mapped_column(String(80));strategy:Mapped[str|None]=mapped_column(String(60));priority:Mapped[str]=mapped_column(String(30),index=True);scheduled_start:Mapped[str|None]=mapped_column(String(40));scheduled_end:Mapped[str|None]=mapped_column(String(40));deadline:Mapped[str|None]=mapped_column(String(40));assigned_resource:Mapped[str|None]=mapped_column(Text);required_parts:Mapped[str|None]=mapped_column(Text);estimated_cost:Mapped[float|None]=mapped_column(Float);status:Mapped[str]=mapped_column(String(30),index=True);blocking_reason:Mapped[str|None]=mapped_column(Text);created_at:Mapped[str]=mapped_column(String(40),default=now);updated_at:Mapped[str]=mapped_column(String(40),default=now,onupdate=now)
class MaintenanceSchedule(IdMixin,Base):
    __tablename__="maintenance_schedule";work_order_id:Mapped[str]=mapped_column(String(80),index=True);equipment_id:Mapped[str]=mapped_column(String(80),index=True);scheduled_start:Mapped[str|None]=mapped_column(String(40));scheduled_end:Mapped[str|None]=mapped_column(String(40));assigned_resource:Mapped[str|None]=mapped_column(Text);priority:Mapped[str]=mapped_column(String(30),index=True);status:Mapped[str]=mapped_column(String(30),index=True);deadline_respected:Mapped[bool]=mapped_column(Boolean)
class AgentHealth(IdMixin,Base):
    __tablename__="agent_health";timestamp:Mapped[str]=mapped_column(String(40),index=True);agent_id:Mapped[str]=mapped_column(String(100),index=True);jid:Mapped[str]=mapped_column(String(100));status:Mapped[str]=mapped_column(String(30),index=True);last_heartbeat:Mapped[str|None]=mapped_column(String(40));messages_processed:Mapped[int]=mapped_column(Integer,default=0);errors_count:Mapped[int]=mapped_column(Integer,default=0);queue_size:Mapped[int]=mapped_column(Integer,default=0);average_processing_time_ms:Mapped[float]=mapped_column(Float,default=0)
class AgentMessage(IdMixin,Base):
    __tablename__="agent_messages";timestamp:Mapped[str]=mapped_column(String(40),index=True);message_id:Mapped[str]=mapped_column(String(80),unique=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);sender_agent:Mapped[str]=mapped_column(String(100),index=True);receiver_agent:Mapped[str]=mapped_column(String(100),index=True);message_type:Mapped[str]=mapped_column(String(80),index=True);performative:Mapped[str|None]=mapped_column(String(40));protocol:Mapped[str|None]=mapped_column(String(60));equipment_id:Mapped[str|None]=mapped_column(String(80),index=True);body:Mapped[str|None]=mapped_column(Text)
class SystemEvent(IdMixin,Base):
    __tablename__="system_events";timestamp:Mapped[str]=mapped_column(String(40),index=True);event_type:Mapped[str]=mapped_column(String(80),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str|None]=mapped_column(String(80),index=True);priority:Mapped[str|None]=mapped_column(String(30),index=True);payload:Mapped[str]=mapped_column(Text,default="{}")
class SystemDecision(IdMixin,Base):
    __tablename__="system_decisions";timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str]=mapped_column(String(80),index=True);equipment_id:Mapped[str|None]=mapped_column(String(80),index=True);priority:Mapped[str|None]=mapped_column(String(30),index=True);decision:Mapped[str]=mapped_column(String(80));explanation:Mapped[str|None]=mapped_column(Text);payload:Mapped[str]=mapped_column(Text,default="{}")
class Alert(IdMixin,Base):
    __tablename__="alerts";alert_id:Mapped[str]=mapped_column(String(80),unique=True,index=True);timestamp:Mapped[str]=mapped_column(String(40),index=True);trace_id:Mapped[str|None]=mapped_column(String(80),index=True);equipment_id:Mapped[str|None]=mapped_column(String(80),index=True);level:Mapped[str]=mapped_column(String(30),index=True);title:Mapped[str]=mapped_column(String(160));message:Mapped[str]=mapped_column(Text);acknowledged:Mapped[bool]=mapped_column(Boolean,index=True,default=False);acknowledged_at:Mapped[str|None]=mapped_column(String(40))
class PipelineTrace(IdMixin,Base):
    __tablename__="pipeline_traces";trace_id:Mapped[str]=mapped_column(String(80),unique=True,index=True);equipment_id:Mapped[str|None]=mapped_column(String(80),index=True);started_at:Mapped[str]=mapped_column(String(40),index=True);completed_at:Mapped[str|None]=mapped_column(String(40));status:Mapped[str]=mapped_column(String(30),index=True);steps_count:Mapped[int]=mapped_column(Integer,default=0);last_step:Mapped[str|None]=mapped_column(String(80));duration_ms:Mapped[float|None]=mapped_column(Float)
class SystemRun(IdMixin,Base):
    __tablename__="system_runs";run_id:Mapped[str]=mapped_column(String(80),unique=True,index=True);scenario:Mapped[str]=mapped_column(String(60),index=True);mode:Mapped[str]=mapped_column(String(30));status:Mapped[str]=mapped_column(String(30),index=True);started_at:Mapped[str]=mapped_column(String(40),index=True);completed_at:Mapped[str|None]=mapped_column(String(40));measurements_processed:Mapped[int]=mapped_column(Integer,default=0);messages_processed:Mapped[int]=mapped_column(Integer,default=0);process_id:Mapped[int|None]=mapped_column(Integer);error_message:Mapped[str|None]=mapped_column(Text)

ALL_MODELS=(Asset,SensorMeasurement,AnomalyResult,FaultDiagnosis,RULPrediction,MaintenanceRecommendation,WorkOrder,MaintenanceSchedule,AgentHealth,AgentMessage,SystemEvent,SystemDecision,Alert,PipelineTrace,SystemRun)
